# Generated by Django 2.0.3 on 2018-03-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('ticket_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('catagory', models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')])),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Signup')),
            ],
        ),
    ]
