# Generated by Django 2.0.3 on 2018-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetail',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
