# Generated by Django 2.0.3 on 2018-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_ticketdetail_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
