# Generated by Django 2.0.3 on 2018-03-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20180326_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newcomment', models.CharField(blank=True, max_length=256, null=True)),
                ('admincomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Signup')),
                ('usercomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.TicketDetail')),
            ],
        ),
    ]
