# Generated by Django 2.0.3 on 2018-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_auto_20180326_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsignup',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
